name: Build and Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy-app:
    name: App Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1

    - name: Setup NodeJS and Cache
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci --force
      
    - name: Build App
      run: npm run actions:build:prod

    - name: Deploy
      working-directory: ./dist/portfolio
      run: | 
        aws s3 cp ./ s3://portfolio.thuthuka.me --recursive
        aws cloudfront create-invalidation --distribution-id EWQ45ZR3PFOX9 --paths '/*'